# Generated by Django 6.0.6 on 2026-06-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.CharField(choices=[('hall1', 'Основной зал'), ('hall2', 'Зал №2')], default='hall1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='hall1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='hall1', max_length=20),
            preserve_default=False,
        ),
    ]
