# Generated by Django 6.0.6 on 2026-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_hall_booking_name_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'Стол 1'), (2, 'Стол 2'), (3, 'Стол 3'), (4, 'Стол 4'), (5, 'Стол 5'), (6, 'Стол 6'), (7, 'Стол 7'), (8, 'Стол 8')]),
        ),
    ]
